import {
  ACTIVE_IMAGE_LOCATION,
  CONFIRM_UPLOAD_IMAGE_IMAGE_LOCATION,
  CREATE_SINGLE_IMAGE_LOCATION,
  DELL_IMAGE_LOCATION,
  GET_ALL_IMAGE_LOCATION,
  GET_IMAGE_LOCATION_WITH_ID,
  INACTIVE_IMAGE_LOCATION,
  SEARCH_IMAGE_LOCATION,
  UPDATE_SINGLE_IMAGE_LOCATION,
  UPLOAD_IMAGE_IMAGE_LOCATION,
  DELL_IMG_SINGLE_IMAGE_LOCATION
} from "./constants";

export const actGetAllImageLocation = (...args) => ({
  type: GET_ALL_IMAGE_LOCATION,
  args
});

export const actDelImageLocation = (...args) => ({
  type: DELL_IMAGE_LOCATION,
  args
});

