export const REDIRECT_AFTER_LOGIN_SUCCESS = "/dashboard";
export const REDIRECT_AFTER_REGISTER_SUCCESS = "/login";
export const REDIRECT_AFTER_FORGOTEMAIL_SUCCESS = "/forgot";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const FORGOTEMAIL = "FORGOTEMAIL";
export const FORGOTEMAIL_SUCCESS = "FORGOTEMAIL_SUCCESS";
export const FORGOTEMAIL_FAILED = "FORGOTEMAIL_FAILED";

export const RESETPASSWORD = "RESETPASSWORD";
export const RESETPASSWORD_SUCCESS = "RESETPASSWORD_SUCCESS";
export const RESETPASSWORD_FAILED = "RESETPASSWORD_FAILED";

export const CHANGEPASSWORD = "CHANGEPASSWORD";
export const CHANGEPASSWORDSUCCESS = "CHANGEPASSWORDSUCCESS";
export const CHANGEPASSWORDFAILED = "CHANGEPASSWORDFAILED";

export const CHANGEINFO = "CHANGEINFO";
export const CHANGEINFOSUCCESS = "CHANGEINFOSUCCESS";
export const CHANGEINFOFAILED = "CHANGEINFOFAILED";
