export const GET_USER_ACTIVITY = "GET_USER_ACTIVITY";
export const GET_USER_ACTIVITY_SUCCESS = "GET_USER_ACTIVITY_SUCCESS";
export const GET_USER_ACTIVITY_FAILED = "GET_USER_ACTIVITY_FAILED";

export const GET_INFO = "GET_INFO";
export const GET_INFO_SUCCESS = "GET_INFO_SUCCESS";
export const GET_INFO_FAILED = "GET_INFO_FAILED";

export const GET_PAYMENT_METHOD = "GET_PAYMENT_METHOD";
export const GET_PAYMENT_METHOD_SUCCESS = "GET_PAYMENT_METHOD_SUCCESS";
export const GET_PAYMENT_METHOD_FAILED = "GET_PAYMENT_METHOD_FAILED";

export const GET_BALANCE = "GET_BALANCE";
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCE_FAILED = "GET_BALANCE_FAILED";

export const GET_TYPE_SERVICES = "GET_TYPE_SERVICES";
export const GET_TYPE_SERVICES_SUCCESS = "GET_TYPE_SERVICES_SUCCESS";
export const GET_TYPE_SERVICES_FAILED = "GET_TYPE_SERVICES_FAILED";

export const ADVERTISING = "ADVERTISING";
export const ADVERTISINGSUCCESS = "ADVERTISINGSUCCESS";
export const ADVERTISINGFAILED = "ADVERTISINGFAILED";

export const ADVERTISING_INSTAGRAM = "ADVERTISING_INSTAGRAM";
export const ADVERTISING_INSTAGRAMSUCCESS = "ADVERTISING_INSTAGRAMSUCCESS";
export const ADVERTISING_INSTAGRAMFAILED = "ADVERTISING_INSTAGRAMFAILED";

export const BUF_FOLLOW_V2 = "BUF_FOLLOW_V2";
export const BUF_FOLLOW_V2SUCCESS = "BUF_FOLLOW_V2SUCCESS";
export const BUF_FOLLOW_V2FAILED = "BUF_FOLLOW_V2FAILED";

export const BUFF_VIDEO_V2 = "BUFF_VIDEO_V2";
export const BUFF_VIDEO_V2SUCCESS = "BUFF_VIDEO_V2SUCCESS";
export const BUFF_VIDEO_V2FAILED = "BUFF_VIDEO_V2FAILED";
